const express=require('express'); const http=require('http'); const path=require('path'); const bcrypt=require('bcryptjs'); const jwt=require('jsonwebtoken'); const rateLimit=require('express-rate-limit'); const {Server}=require('socket.io'); const Database=require('better-sqlite3');
require('dotenv').config?.();
const PORT=process.env.PORT||5500, SECRET=process.env.JWT_SECRET||'dev-secret-change-me';
const app=express(), server=http.createServer(app), io=new Server(server); app.use(express.json({limit:'1mb'})); app.use(rateLimit({windowMs:60000,max:240}));
const db=new Database(path.join(__dirname,'../database/deadfall.db')); db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'player',xp INTEGER NOT NULL DEFAULT 0,level INTEGER NOT NULL DEFAULT 1,kills INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen TEXT); CREATE TABLE IF NOT EXISTS cities(user_id INTEGER PRIMARY KEY,city_name TEXT NOT NULL DEFAULT 'New Haven',food INTEGER NOT NULL DEFAULT 1200,wood INTEGER NOT NULL DEFAULT 900,metal INTEGER NOT NULL DEFAULT 700,fuel INTEGER NOT NULL DEFAULT 500,wall INTEGER NOT NULL DEFAULT 100,threat INTEGER NOT NULL DEFAULT 12,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id)); CREATE TABLE IF NOT EXISTS buildings(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,name TEXT NOT NULL,level INTEGER NOT NULL DEFAULT 1,unique(user_id,name),FOREIGN KEY(user_id) REFERENCES users(id)); CREATE TABLE IF NOT EXISTS army(user_id INTEGER NOT NULL,type TEXT NOT NULL,count INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(user_id,type)); CREATE TABLE IF NOT EXISTS missions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,code TEXT NOT NULL,progress INTEGER NOT NULL DEFAULT 0,claimed INTEGER NOT NULL DEFAULT 0,unique(user_id,code)); CREATE TABLE IF NOT EXISTS admin_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,admin_id INTEGER,action TEXT,details TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
const insBuilding=db.prepare('INSERT OR IGNORE INTO buildings(user_id,name,level) VALUES(?,?,1)'), insArmy=db.prepare('INSERT OR IGNORE INTO army(user_id,type,count) VALUES(?,?,?)'), insMission=db.prepare('INSERT OR IGNORE INTO missions(user_id,code,progress) VALUES(?,?,0)');
function seedUser(u){['Town Hall','Farm','Lumber Yard','Barracks','Workshop','Watchtower','Hospital','Armory'].forEach(x=>insBuilding.run(u.id,x));[['Riflemen',20],['Guards',10],['Scouts',5]].forEach(x=>insArmy.run(u.id,...x));['streets','gatherer','firstblood','builder'].forEach(x=>insMission.run(u.id,x));}
const adminEmail=process.env.ADMIN_EMAIL||'admin@deadfall.local'; if(!db.prepare('SELECT id FROM users WHERE email=?').get(adminEmail)){const p=bcrypt.hashSync(process.env.ADMIN_PASSWORD||'ChangeMe_123!',12); const r=db.prepare('INSERT INTO users(email,password,name,role) VALUES(?,?,?,?)').run(adminEmail,p,'Administrator','admin'); const u=db.prepare('SELECT * FROM users WHERE id=?').get(r.lastInsertRowid); db.prepare('INSERT INTO cities(user_id) VALUES(?)').run(u.id); seedUser(u);}
function token(u){return jwt.sign({id:u.id,role:u.role},SECRET,{expiresIn:'7d'})} function auth(req,res,next){try{const p=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),SECRET); req.user=db.prepare('SELECT id,email,name,role,xp,level,kills FROM users WHERE id=?').get(p.id); if(!req.user)return res.sendStatus(401); next()}catch(e){res.sendStatus(401)}} function admin(req,res,next){if(req.user.role!=='admin')return res.sendStatus(403);next()}
function state(id){const u=db.prepare('SELECT id,email,name,role,xp,level,kills FROM users WHERE id=?').get(id); const c=db.prepare('SELECT * FROM cities WHERE user_id=?').get(id); const buildings=db.prepare('SELECT name,level FROM buildings WHERE user_id=?').all(id); const army=db.prepare('SELECT type,count FROM army WHERE user_id=?').all(id); const missions=db.prepare('SELECT code,progress,claimed FROM missions WHERE user_id=?').all(id); return {user:u,city:c,buildings,army,missions,online:io.sockets.adapter.rooms.get('world')?.size||0};}
app.post('/api/auth/register',(req,res)=>{const {email,password,name}=req.body||{}; if(!/^\S+@\S+\.\S+$/.test(email||'')||!password||password.length<8||!name)return res.status(400).json({error:'Valid name, email and 8+ character password required'}); try{const r=db.prepare('INSERT INTO users(email,password,name) VALUES(?,?,?)').run(email.toLowerCase(),bcrypt.hashSync(password,12),String(name).slice(0,30)); db.prepare('INSERT INTO cities(user_id) VALUES(?)').run(r.lastInsertRowid); const u=db.prepare('SELECT * FROM users WHERE id=?').get(r.lastInsertRowid); seedUser(u); res.json({token:token(u),state:state(u.id)})}catch(e){res.status(409).json({error:'Email already registered'})}});
app.post('/api/auth/login',(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE email=?').get(String(req.body.email||'').toLowerCase()); if(!u||!bcrypt.compareSync(req.body.password||'',u.password))return res.status(401).json({error:'Invalid credentials'}); db.prepare('UPDATE users SET last_seen=CURRENT_TIMESTAMP WHERE id=?').run(u.id); res.json({token:token(u),state:state(u.id)})});
app.get('/api/state',auth,(req,res)=>res.json(state(req.user.id)));
app.post('/api/action/build',auth,(req,res)=>{const {name}=req.body; const costs={Farm:[120,80,30,0], 'Lumber Yard':[100,120,25,0],Barracks:[180,140,80,20],Workshop:[200,180,120,50],Watchtower:[160,120,100,30],Hospital:[220,160,150,50],Armory:[300,240,220,100]}; if(!costs[name])return res.status(400).json({error:'Unknown building'}); const c=db.prepare('SELECT * FROM cities WHERE user_id=?').get(req.user.id), b=db.prepare('SELECT * FROM buildings WHERE user_id=? AND name=?').get(req.user.id,name); const mult=b.level; const [f,w,m,fu]=costs[name].map(v=>v*mult); if(c.food<f||c.wood<w||c.metal<m||c.fuel<fu)return res.status(400).json({error:'Not enough resources'}); db.transaction(()=>{db.prepare('UPDATE cities SET food=food-?,wood=wood-?,metal=metal-?,fuel=fuel-?,updated_at=CURRENT_TIMESTAMP WHERE user_id=?').run(f,w,m,fu,req.user.id); db.prepare('UPDATE buildings SET level=level+1 WHERE user_id=? AND name=?').run(req.user.id,name); db.prepare('UPDATE users SET xp=xp+? WHERE id=?').run(50,req.user.id)})(); res.json(state(req.user.id)); io.to('world').emit('world:update',{type:'building',player:req.user.name});});
app.post('/api/action/mission',auth,(req,res)=>{const code=req.body.code; const m=db.prepare('SELECT * FROM missions WHERE user_id=? AND code=?').get(req.user.id,code); if(!m||m.claimed)return res.status(400).json({error:'Mission unavailable'}); const need={streets:10,gatherer:100,firstblood:1,builder:3}[code]||1; const prog=Math.min(need,m.progress+(req.body.amount||1)); if(prog<need){db.prepare('UPDATE missions SET progress=? WHERE id=?').run(prog,m.id);return res.json(state(req.user.id))} db.prepare('UPDATE missions SET progress=?,claimed=1 WHERE id=?').run(prog,m.id); db.prepare('UPDATE users SET xp=xp+100,kills=kills+? WHERE id=?').run(code==='firstblood'?1:0,req.user.id); db.prepare('UPDATE cities SET food=food+250,wood=wood+200,metal=metal+150,fuel=fuel+100 WHERE user_id=?').run(req.user.id); res.json(state(req.user.id));});
app.post('/api/action/combat',auth,(req,res)=>{const c=db.prepare('SELECT * FROM cities WHERE user_id=?').get(req.user.id); const soldiers=db.prepare('SELECT SUM(count) n FROM army WHERE user_id=?').get(req.user.id).n||0; if(soldiers<5)return res.status(400).json({error:'Need at least 5 troops'}); const enemy=Math.floor(Math.random()*70)+20; const power=soldiers+Math.floor(Math.random()*40); const win=power>=enemy; db.transaction(()=>{db.prepare('UPDATE army SET count=MAX(0,count-?) WHERE user_id=? AND type=?').run(win?Math.max(1,Math.floor(enemy/20)):Math.max(2,Math.floor(soldiers/4)),req.user.id,'Riflemen'); if(win)db.prepare('UPDATE users SET xp=xp+120,kills=kills+? WHERE id=?').run(Math.max(1,Math.floor(enemy/15)),req.user.id); db.prepare('UPDATE cities SET threat=MAX(0,threat+?) WHERE user_id=?').run(win?-5:8,req.user.id)})(); res.json({win,enemy,power,state:state(req.user.id)});});
app.get('/api/rankings',auth,(req,res)=>res.json(db.prepare('SELECT name,level,xp,kills FROM users WHERE role=\'player\' ORDER BY xp DESC LIMIT 50').all()));
app.get('/api/map',auth,(req,res)=>res.json(db.prepare('SELECT u.id,u.name,c.city_name city,c.threat,u.level,u.kills FROM users u JOIN cities c ON c.user_id=u.id WHERE u.role=\'player\' ORDER BY u.level DESC').all()));
app.get('/api/admin/players',auth,admin,(req,res)=>res.json(db.prepare('SELECT u.id,u.email,u.name,u.role,u.xp,u.level,u.kills,u.created_at,c.food,c.wood,c.metal,c.fuel,c.wall,c.threat FROM users u JOIN cities c ON c.user_id=u.id ORDER BY u.created_at DESC').all()));
app.post('/api/admin/give',auth,admin,(req,res)=>{const {userId,resource,amount}=req.body; if(!['food','wood','metal','fuel'].includes(resource))return res.sendStatus(400); db.prepare(`UPDATE cities SET ${resource}=${resource}+? WHERE user_id=?`).run(Math.max(-100000,Math.min(100000,Number(amount)||0)),userId); db.prepare('INSERT INTO admin_logs(admin_id,action,details) VALUES(?,?,?)').run(req.user.id,'resource',`${resource}:${amount} user:${userId}`); io.to('world').emit('world:update',{type:'admin'}); res.json({ok:true});});
app.post('/api/admin/horde',auth,admin,(req,res)=>{const amount=Math.max(1,Math.min(1000,Number(req.body.amount)||50)); db.prepare('UPDATE cities SET threat=MIN(100,threat+?)').run(Math.floor(amount/10)); db.prepare('INSERT INTO admin_logs(admin_id,action,details) VALUES(?,?,?)').run(req.user.id,'horde',`strength:${amount}`); io.to('world').emit('world:event',{title:'GLOBAL HORDE',text:`A horde of ${amount} infected has entered the wasteland.`}); res.json({ok:true});});
app.post('/api/admin/broadcast',auth,admin,(req,res)=>{const text=String(req.body.text||'').slice(0,300); io.to('world').emit('world:event',{title:'COMMAND BROADCAST',text}); db.prepare('INSERT INTO admin_logs(admin_id,action,details) VALUES(?,?,?)').run(req.user.id,'broadcast',text); res.json({ok:true});});
app.use(express.static(path.join(__dirname,'../client'))); app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'../client/index.html')));
io.on('connection',socket=>{socket.on('join',tokenStr=>{try{const p=jwt.verify(tokenStr,SECRET); socket.data.userId=p.id; socket.join('world'); socket.emit('world:presence',{online:io.sockets.adapter.rooms.get('world')?.size||1}); socket.broadcast.to('world').emit('world:presence',{online:io.sockets.adapter.rooms.get('world')?.size||1})}catch{socket.disconnect()}})});
setInterval(()=>{db.prepare('UPDATE cities SET food=MIN(100000,food+5),wood=MIN(100000,wood+4),metal=MIN(100000,metal+3),fuel=MIN(100000,fuel+2),updated_at=CURRENT_TIMESTAMP').run(); io.to('world').emit('world:tick',{ts:Date.now()})},60000);
server.listen(PORT,()=>console.log(`DEADFALL online server running on http://localhost:${PORT}`));
